<?php
namespace common\widgets;

use yii\data\ActiveDataProvider;

class ExportMenu extends \kartik\export\ExportMenu
{
    public $formatter = ['class' => 'common\components\Formatter', 'nullDisplay' => ''];
    public $exportFormView = '@vendor/kartik-v/yii2-export/views/_form';
    public $exportColumnsView = '@vendor/kartik-v/yii2-export/views/_columns';
    public $afterSaveView = '@vendor/kartik-v/yii2-export/views/_view';
    public $exportConfig
        = [
            ExportMenu::FORMAT_HTML  => false,
            ExportMenu::FORMAT_TEXT  => false,
            ExportMenu::FORMAT_PDF   => false,
            ExportMenu::FORMAT_EXCEL => false,
        ];
    public $target = ExportMenu::TARGET_BLANK;

    public $columnSelectorOptions
        = [
            'label' => '',
        ];
    public $dropdownOptions
        = [
            'label' => 'Экспорт результатов',
            'class' => 'btn btn-default'
        ];
    public $showConfirmAlert = false;
    public $batchSize = 10000;
    public $stream = false;
    public $folder = '@webroot/assets';
    public $linkPath = '/assets';
    public $streamAfterSave = false;
    public $deleteAfterSave = true;

    public function init()
    {
        $this->dataProvider = clone $this->dataProvider;
//        if (\Yii::$app->request->post('export_type')) {
//            ob_get_clean();
//        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        ini_set('max_execution_time', 0);
        return parent::run();
    }
}